In [2]:
##IMPORTAÇÃO DAS BIBLIOTECAS NECESSÁRIAS
import pandas as pd

In [24]:
##EXTRAÇÃO
df = pd.read_csv("ocorrencia.csv", sep=";", parse_dates=['ocorrencia_dia'], dayfirst=True)
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0

In [4]:
##retornar o valor da linha 1 e coluna 'ocorrencia_cidade'
df.loc[1, 'ocorrencia_cidade']

'BELÉM'

In [5]:
##retornar todas as colunas da linha 3
df.loc[3]

codigo_ocorrencia                         39527
codigo_ocorrencia2                        39527
ocorrencia_classificacao               ACIDENTE
ocorrencia_cidade            LUCAS DO RIO VERDE
ocorrencia_uf                                MT
ocorrencia_aerodromo                       ****
ocorrencia_dia              2010-01-04 00:00:00
ocorrencia_hora                        17:30:00
total_recomendacoes                           0
Name: 3, dtype: object

In [6]:
##retornar todas as colunas da linha 1 a 3
df.loc[1:3]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-01-04,17:30:00,0

In [7]:
##retornar a linha 10 e 40
df.loc[[10,40]]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,39789,39789,INCIDENTE,SÃO PEDRO DO SUL,RS,****,2010-01-10,21:30:00,0
40,39158,39158,INCIDENTE,BELÉM,PA,****,2010-01-28,16:00:00,0

In [8]:
##retornar todas as linhas (representado por ":") da coluna 'ocorrencia_cidade'
df.loc[:,'ocorrencia_cidade']

0           RIO DE JANEIRO
1                    BELÉM
2           RIO DE JANEIRO
3       LUCAS DO RIO VERDE
4                  PELOTAS
               ...
6109                RECIFE
6110           PORTO VELHO
6111                 BELÉM
6112            DOM AQUINO
6113              CAMPINAS
Name: ocorrencia_cidade, Length: 6114, dtype: object

In [9]:
##verificar se uma coluna é unica
df.codigo_ocorrencia.is_unique

True

In [10]:
##verificar como a alteração de um indice de um dataframe vai ficar
df.set_index('codigo_ocorrencia')

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
codigo_ocorrencia,,,,,,,,
40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-01-03,12:00:00,0
40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-01-04,17:30:00,0
40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
...,...,...,...,...,...,...,...,...
80245,80245,INCIDENTE,RECIFE,PE,SBRF,2021-08-15,15:05:00,0
80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,2021-08-16,02:30:00,0
80251,80251,INCIDENTE,BELÉM,PA,SBBE,2021-08-17,15:45:00,0
80257,80257,ACIDENTE,DOM AQUINO,MT,****,2021-08-18,16:00:00,0
80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [11]:
##alteração de um indice de um dataframe :: uso do inplace=True
df.set_index('codigo_ocorrencia', inplace=True)

In [12]:
df.head()

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
codigo_ocorrencia,,,,,,,,
40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-01-03,12:00:00,0
40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-01-04,17:30:00,0
40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0

In [13]:
##consultar pelo novo indice alterado
df.loc[40324]

codigo_ocorrencia2                        40324
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                       PELOTAS
ocorrencia_uf                                RS
ocorrencia_aerodromo                       SBPK
ocorrencia_dia              2010-01-05 00:00:00
ocorrencia_hora                        19:25:00
total_recomendacoes                           0
Name: 40324, dtype: object

In [14]:
##Excluir o index alterado e voltar para o index original
df.reset_index(drop=True, inplace=True)

In [15]:
df.head()

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-01-03,12:00:00,0
1,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-01-04,17:30:00,0
4,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0

In [16]:
df.loc[0,'ocorrencia_aerodromo'] = ''

In [17]:
df.head(1)

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,INCIDENTE,RIO DE JANEIRO,RJ,,2010-01-03,12:00:00,0

In [18]:
##criar uma nova coluna a partir de uma que já existe
df['ocorrencia_uf_bkp'] = df.ocorrencia_uf

In [19]:
df.head(1)

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_uf_bkp
0,40211,INCIDENTE,RIO DE JANEIRO,RJ,,2010-01-03,12:00:00,0,RJ

In [20]:
##Alterar uma coluna do dataframe a partir de uma condição
df.loc[df.ocorrencia_uf == 'SP', ['ocorrencia_classificacao']] = 'GRAVE'

In [21]:
df.loc[df.ocorrencia_uf == 'SP']

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_uf_bkp
11,40069,GRAVE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8,SP
16,39809,GRAVE,SÃO PAULO,SP,****,2010-01-15,15:00:00,0,SP
18,39828,GRAVE,SANTOS,SP,****,2010-01-15,17:45:00,0,SP
26,39847,GRAVE,SOROCABA,SP,****,2010-01-20,13:10:00,0,SP
27,39768,GRAVE,CAMPINAS,SP,****,2010-01-21,20:45:00,0,SP
...,...,...,...,...,...,...,...,...,...
6084,80234,GRAVE,SÃO PAULO,SP,SBSP,2021-07-26,13:20:00,0,SP
6085,80208,GRAVE,SÃO PAULO,SP,SBMT,2021-07-27,19:45:00,0,SP
6104,80238,GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0,SP
6108,80244,GRAVE,BRAGANÇA PAULISTA,SP,SBBP,2021-08-15,15:20:00,0,SP
6113,80259,GRAVE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0,SP

In [22]:
##consultar todo o dataframe
df

,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_uf_bkp
0,40211,INCIDENTE,RIO DE JANEIRO,RJ,,2010-01-03,12:00:00,0,RJ
1,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0,PA
2,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,RJ
3,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-01-04,17:30:00,0,MT
4,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0,RS
...,...,...,...,...,...,...,...,...,...
6109,80245,INCIDENTE,RECIFE,PE,SBRF,2021-08-15,15:05:00,0,PE
6110,80247,INCIDENTE,PORTO VELHO,RO,SBPV,2021-08-16,02:30:00,0,RO
6111,80251,INCIDENTE,BELÉM,PA,SBBE,2021-08-17,15:45:00,0,PA
6112,80257,ACIDENTE,DOM AQUINO,MT,****,2021-08-18,16:00:00,0,MT
6113,80259,GRAVE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0,SP

ocorrencia_uf
**

ocorrencia_aerodromo
###!
####
****
*****

ocorrencia_hora
NULL

In [33]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,****,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,****,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0

In [43]:
##Atribuir um valor nao informados, podemos utilizar o "NA" do pandas
df.loc[df.ocorrencia_aerodromo == '****', ['ocorrencia_aerodromo']] = pd.NA

In [44]:
df.head

<bound method NDFrame.head of       codigo_ocorrencia  codigo_ocorrencia2 ocorrencia_classificacao  \
0                 40211               40211                INCIDENTE
1                 40349               40349                INCIDENTE
2                 40351               40351                INCIDENTE
3                 39527               39527                 ACIDENTE
4                 40324               40324                INCIDENTE
...                 ...                 ...                      ...
6109              80245               80245                INCIDENTE
6110              80247               80247                INCIDENTE
6111              80251               80251                INCIDENTE
6112              80257               80257                 ACIDENTE
6113              80259               80259                INCIDENTE

       ocorrencia_cidade ocorrencia_uf ocorrencia_aerodromo ocorrencia_dia  \
0         RIO DE JANEIRO            RJ                 <NA>     2010-01-03
1                  BELÉM            PA                 SBBE     2010-01-03
2         RIO DE JANEIRO            RJ                 SBRJ     2010-01-03
3     LUCAS DO RIO VERDE            MT                 <NA>     2010-01-04
4                PELOTAS            RS                 SBPK     2010-01-05
...                  ...           ...                  ...            ...
6109              RECIFE            PE                 SBRF     2021-08-15
6110         PORTO VELHO            RO                 SBPV     2021-08-16
6111               BELÉM            PA                 SBBE     2021-08-17
6112          DOM AQUINO            MT                 <NA>     2021-08-18
6113            CAMPINAS            SP                 SBKP     2021-08-18

     ocorrencia_hora  total_recomendacoes
0           12:00:00                    0
1           11:05:00                    0
2           03:00:00                    0
3           17:30:00                    0
4           19:25:00                    0
...              ...                  ...
6109        15:05:00                    0
6110        02:30:00                    0
6111        15:45:00                    0
6112        16:00:00                    0
6113        12:45:00                    0

[6114 rows x 9 columns]>

In [47]:
## A função replace permite fazer uma alteração no DF como um todo
df.replace(['###!','####','****','*****', 'NULL'], pd.NA, inplace=True)

In [54]:
## verificar quantos registros temos como "não informados" no nosso dataframe - 1º forma
df.isna().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  0
ocorrencia_aerodromo        2456
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [55]:
## verificar quantos registros temos como "não informados" no nosso dataframe - 2º forma
df.isnull().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  0
ocorrencia_aerodromo        2456
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [58]:
## atribuir um valor nos campos que tem valores não informados
df.fillna(10, inplace=True)

In [59]:
df.isnull().sum()

codigo_ocorrencia           0
codigo_ocorrencia2          0
ocorrencia_classificacao    0
ocorrencia_cidade           0
ocorrencia_uf               0
ocorrencia_aerodromo        0
ocorrencia_dia              0
ocorrencia_hora             0
total_recomendacoes         0
dtype: int64

In [60]:
df.replace([10], pd.NA, inplace=True)

In [62]:
df.isnull().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  0
ocorrencia_aerodromo        2456
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            2
dtype: int64

In [64]:
## alterar o "valor nao informado" apenas em uma coluna especifica
df.fillna(value={'total_recomendacoes':10}, inplace=True)

In [65]:
df.isnull().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  0
ocorrencia_aerodromo        2456
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [66]:
df['total_recomendacoes_bkp'] =  df.total_recomendacoes

In [67]:
## excluir uma coluna :: eixo:0 (linha) // eixo:1 (coluna)
df.drop(['total_recomendacoes_bkp'], axis=1, inplace=True)

In [ ]:
## excluir todos os valores nao informados :: exclui a linha toda
df.dropana()

In [69]:
## excluir todos os valores nao informados :: por determinada coluna apenas
df.dropna(subset=['ocorrencia_uf'])

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,<NA>,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,<NA>,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
...,...,...,...,...,...,...,...,...,...
6109,80245,80245,INCIDENTE,RECIFE,PE,SBRF,2021-08-15,15:05:00,0
6110,80247,80247,INCIDENTE,PORTO VELHO,RO,SBPV,2021-08-16,02:30:00,0
6111,80251,80251,INCIDENTE,BELÉM,PA,SBBE,2021-08-17,15:45:00,0
6112,80257,80257,ACIDENTE,DOM AQUINO,MT,<NA>,2021-08-18,16:00:00,0
6113,80259,80259,INCIDENTE,CAMPINAS,SP,SBKP,2021-08-18,12:45:00,0

In [72]:
## retirar valores duplicados
df.drop_duplicates(inplace=True)